// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: push/push.proto

package push

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushMsgService_PushMsg_FullMethodName              = "/openim.push.PushMsgService/PushMsg"
	PushMsgService_DelUserPushToken_FullMethodName     = "/openim.push.PushMsgService/DelUserPushToken"
	PushMsgService_GetPushSettings_FullMethodName      = "/openim.push.PushMsgService/GetPushSettings"
	PushMsgService_SetPushSettings_FullMethodName      = "/openim.push.PushMsgService/SetPushSettings"
	PushMsgService_ImportPushSettings_FullMethodName   = "/openim.push.PushMsgService/ImportPushSettings"
	PushMsgService_ExportPushSettings_FullMethodName   = "/openim.push.PushMsgService/ExportPushSettings"
	PushMsgService_VerifyPushProvider_FullMethodName   = "/openim.push.PushMsgService/VerifyPushProvider"
	PushMsgService_TestPush_FullMethodName             = "/openim.push.PushMsgService/TestPush"
	PushMsgService_GetUserPushDevices_FullMethodName   = "/openim.push.PushMsgService/GetUserPushDevices"
	PushMsgService_DelUserPushDevice_FullMethodName    = "/openim.push.PushMsgService/DelUserPushDevice"
	PushMsgService_GetPushStats_FullMethodName         = "/openim.push.PushMsgService/GetPushStats"
	PushMsgService_GetPushSettingsAudit_FullMethodName = "/openim.push.PushMsgService/GetPushSettingsAudit"
)

// PushMsgServiceClient is the client API for PushMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushMsgServiceClient interface {
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error)
	DelUserPushToken(ctx context.Context, in *DelUserPushTokenReq, opts ...grpc.CallOption) (*DelUserPushTokenResp, error)
	GetPushSettings(ctx context.Context, in *GetPushSettingsReq, opts ...grpc.CallOption) (*GetPushSettingsResp, error)
	SetPushSettings(ctx context.Context, in *SetPushSettingsReq, opts ...grpc.CallOption) (*SetPushSettingsResp, error)
	ImportPushSettings(ctx context.Context, in *ImportPushSettingsReq, opts ...grpc.CallOption) (*ImportPushSettingsResp, error)
	ExportPushSettings(ctx context.Context, in *ExportPushSettingsReq, opts ...grpc.CallOption) (*ExportPushSettingsResp, error)
	VerifyPushProvider(ctx context.Context, in *VerifyPushProviderReq, opts ...grpc.CallOption) (*VerifyPushProviderResp, error)
	TestPush(ctx context.Context, in *TestPushReq, opts ...grpc.CallOption) (*TestPushResp, error)
	GetUserPushDevices(ctx context.Context, in *GetUserPushDevicesReq, opts ...grpc.CallOption) (*GetUserPushDevicesResp, error)
	DelUserPushDevice(ctx context.Context, in *DelUserPushDeviceReq, opts ...grpc.CallOption) (*DelUserPushDeviceResp, error)
	GetPushStats(ctx context.Context, in *GetPushStatsReq, opts ...grpc.CallOption) (*GetPushStatsResp, error)
	GetPushSettingsAudit(ctx context.Context, in *GetPushSettingsAuditReq, opts ...grpc.CallOption) (*GetPushSettingsAuditResp, error)
}

type pushMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushMsgServiceClient(cc grpc.ClientConnInterface) PushMsgServiceClient {
	return &pushMsgServiceClient{cc}
}

func (c *pushMsgServiceClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMsgResp)
	err := c.cc.Invoke(ctx, PushMsgService_PushMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) DelUserPushToken(ctx context.Context, in *DelUserPushTokenReq, opts ...grpc.CallOption) (*DelUserPushTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUserPushTokenResp)
	err := c.cc.Invoke(ctx, PushMsgService_DelUserPushToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) GetPushSettings(ctx context.Context, in *GetPushSettingsReq, opts ...grpc.CallOption) (*GetPushSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPushSettingsResp)
	err := c.cc.Invoke(ctx, PushMsgService_GetPushSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) SetPushSettings(ctx context.Context, in *SetPushSettingsReq, opts ...grpc.CallOption) (*SetPushSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPushSettingsResp)
	err := c.cc.Invoke(ctx, PushMsgService_SetPushSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) ImportPushSettings(ctx context.Context, in *ImportPushSettingsReq, opts ...grpc.CallOption) (*ImportPushSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportPushSettingsResp)
	err := c.cc.Invoke(ctx, PushMsgService_ImportPushSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) ExportPushSettings(ctx context.Context, in *ExportPushSettingsReq, opts ...grpc.CallOption) (*ExportPushSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportPushSettingsResp)
	err := c.cc.Invoke(ctx, PushMsgService_ExportPushSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) VerifyPushProvider(ctx context.Context, in *VerifyPushProviderReq, opts ...grpc.CallOption) (*VerifyPushProviderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPushProviderResp)
	err := c.cc.Invoke(ctx, PushMsgService_VerifyPushProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) TestPush(ctx context.Context, in *TestPushReq, opts ...grpc.CallOption) (*TestPushResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestPushResp)
	err := c.cc.Invoke(ctx, PushMsgService_TestPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) GetUserPushDevices(ctx context.Context, in *GetUserPushDevicesReq, opts ...grpc.CallOption) (*GetUserPushDevicesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPushDevicesResp)
	err := c.cc.Invoke(ctx, PushMsgService_GetUserPushDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) DelUserPushDevice(ctx context.Context, in *DelUserPushDeviceReq, opts ...grpc.CallOption) (*DelUserPushDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUserPushDeviceResp)
	err := c.cc.Invoke(ctx, PushMsgService_DelUserPushDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) GetPushStats(ctx context.Context, in *GetPushStatsReq, opts ...grpc.CallOption) (*GetPushStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPushStatsResp)
	err := c.cc.Invoke(ctx, PushMsgService_GetPushStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushMsgServiceClient) GetPushSettingsAudit(ctx context.Context, in *GetPushSettingsAuditReq, opts ...grpc.CallOption) (*GetPushSettingsAuditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPushSettingsAuditResp)
	err := c.cc.Invoke(ctx, PushMsgService_GetPushSettingsAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushMsgServiceServer is the server API for PushMsgService service.
// All implementations must embed UnimplementedPushMsgServiceServer
// for forward compatibility.
type PushMsgServiceServer interface {
	PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error)
	DelUserPushToken(context.Context, *DelUserPushTokenReq) (*DelUserPushTokenResp, error)
	GetPushSettings(context.Context, *GetPushSettingsReq) (*GetPushSettingsResp, error)
	SetPushSettings(context.Context, *SetPushSettingsReq) (*SetPushSettingsResp, error)
	ImportPushSettings(context.Context, *ImportPushSettingsReq) (*ImportPushSettingsResp, error)
	ExportPushSettings(context.Context, *ExportPushSettingsReq) (*ExportPushSettingsResp, error)
	VerifyPushProvider(context.Context, *VerifyPushProviderReq) (*VerifyPushProviderResp, error)
	TestPush(context.Context, *TestPushReq) (*TestPushResp, error)
	GetUserPushDevices(context.Context, *GetUserPushDevicesReq) (*GetUserPushDevicesResp, error)
	DelUserPushDevice(context.Context, *DelUserPushDeviceReq) (*DelUserPushDeviceResp, error)
	GetPushStats(context.Context, *GetPushStatsReq) (*GetPushStatsResp, error)
	GetPushSettingsAudit(context.Context, *GetPushSettingsAuditReq) (*GetPushSettingsAuditResp, error)
	mustEmbedUnimplementedPushMsgServiceServer()
}

// UnimplementedPushMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushMsgServiceServer struct{}

func (UnimplementedPushMsgServiceServer) PushMsg(context.Context, *PushMsgReq) (*PushMsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushMsg not implemented")
}
func (UnimplementedPushMsgServiceServer) DelUserPushToken(context.Context, *DelUserPushTokenReq) (*DelUserPushTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserPushToken not implemented")
}
func (UnimplementedPushMsgServiceServer) GetPushSettings(context.Context, *GetPushSettingsReq) (*GetPushSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPushSettings not implemented")
}
func (UnimplementedPushMsgServiceServer) SetPushSettings(context.Context, *SetPushSettingsReq) (*SetPushSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPushSettings not implemented")
}
func (UnimplementedPushMsgServiceServer) ImportPushSettings(context.Context, *ImportPushSettingsReq) (*ImportPushSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportPushSettings not implemented")
}
func (UnimplementedPushMsgServiceServer) ExportPushSettings(context.Context, *ExportPushSettingsReq) (*ExportPushSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPushSettings not implemented")
}
func (UnimplementedPushMsgServiceServer) VerifyPushProvider(context.Context, *VerifyPushProviderReq) (*VerifyPushProviderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPushProvider not implemented")
}
func (UnimplementedPushMsgServiceServer) TestPush(context.Context, *TestPushReq) (*TestPushResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestPush not implemented")
}
func (UnimplementedPushMsgServiceServer) GetUserPushDevices(context.Context, *GetUserPushDevicesReq) (*GetUserPushDevicesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPushDevices not implemented")
}
func (UnimplementedPushMsgServiceServer) DelUserPushDevice(context.Context, *DelUserPushDeviceReq) (*DelUserPushDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUserPushDevice not implemented")
}
func (UnimplementedPushMsgServiceServer) GetPushStats(context.Context, *GetPushStatsReq) (*GetPushStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPushStats not implemented")
}
func (UnimplementedPushMsgServiceServer) GetPushSettingsAudit(context.Context, *GetPushSettingsAuditReq) (*GetPushSettingsAuditResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPushSettingsAudit not implemented")
}
func (UnimplementedPushMsgServiceServer) mustEmbedUnimplementedPushMsgServiceServer() {}
func (UnimplementedPushMsgServiceServer) testEmbeddedByValue()                        {}

// UnsafePushMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushMsgServiceServer will
// result in compilation errors.
type UnsafePushMsgServiceServer interface {
	mustEmbedUnimplementedPushMsgServiceServer()
}

func RegisterPushMsgServiceServer(s grpc.ServiceRegistrar, srv PushMsgServiceServer) {
	// If the following call panics, it indicates UnimplementedPushMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushMsgService_ServiceDesc, srv)
}

func _PushMsgService_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_PushMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_DelUserPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserPushTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).DelUserPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_DelUserPushToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).DelUserPushToken(ctx, req.(*DelUserPushTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_GetPushSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).GetPushSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_GetPushSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).GetPushSettings(ctx, req.(*GetPushSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_SetPushSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPushSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).SetPushSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_SetPushSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).SetPushSettings(ctx, req.(*SetPushSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_ImportPushSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportPushSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).ImportPushSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_ImportPushSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).ImportPushSettings(ctx, req.(*ImportPushSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_ExportPushSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportPushSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).ExportPushSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_ExportPushSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).ExportPushSettings(ctx, req.(*ExportPushSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_VerifyPushProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPushProviderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).VerifyPushProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_VerifyPushProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).VerifyPushProvider(ctx, req.(*VerifyPushProviderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_TestPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestPushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).TestPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_TestPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).TestPush(ctx, req.(*TestPushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_GetUserPushDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPushDevicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).GetUserPushDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_GetUserPushDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).GetUserPushDevices(ctx, req.(*GetUserPushDevicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_DelUserPushDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserPushDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).DelUserPushDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_DelUserPushDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).DelUserPushDevice(ctx, req.(*DelUserPushDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_GetPushStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).GetPushStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_GetPushStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).GetPushStats(ctx, req.(*GetPushStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushMsgService_GetPushSettingsAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPushSettingsAuditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMsgServiceServer).GetPushSettingsAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushMsgService_GetPushSettingsAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMsgServiceServer).GetPushSettingsAudit(ctx, req.(*GetPushSettingsAuditReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PushMsgService_ServiceDesc is the grpc.ServiceDesc for PushMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.push.PushMsgService",
	HandlerType: (*PushMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _PushMsgService_PushMsg_Handler,
		},
		{
			MethodName: "DelUserPushToken",
			Handler:    _PushMsgService_DelUserPushToken_Handler,
		},
		{
			MethodName: "GetPushSettings",
			Handler:    _PushMsgService_GetPushSettings_Handler,
		},
		{
			MethodName: "SetPushSettings",
			Handler:    _PushMsgService_SetPushSettings_Handler,
		},
		{
			MethodName: "ImportPushSettings",
			Handler:    _PushMsgService_ImportPushSettings_Handler,
		},
		{
			MethodName: "ExportPushSettings",
			Handler:    _PushMsgService_ExportPushSettings_Handler,
		},
		{
			MethodName: "VerifyPushProvider",
			Handler:    _PushMsgService_VerifyPushProvider_Handler,
		},
		{
			MethodName: "TestPush",
			Handler:    _PushMsgService_TestPush_Handler,
		},
		{
			MethodName: "GetUserPushDevices",
			Handler:    _PushMsgService_GetUserPushDevices_Handler,
		},
		{
			MethodName: "DelUserPushDevice",
			Handler:    _PushMsgService_DelUserPushDevice_Handler,
		},
		{
			MethodName: "GetPushStats",
			Handler:    _PushMsgService_GetPushStats_Handler,
		},
		{
			MethodName: "GetPushSettingsAudit",
			Handler:    _PushMsgService_GetPushSettingsAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push/push.proto",
}
