// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: push/push.proto

package push

import (
	sdkws "github.com/openimsdk/protocol/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMsgReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgData        *sdkws.MsgData         `protobuf:"bytes,1,opt,name=msgData,proto3" json:"msgData"`
	ConversationID string                 `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID"`
	UserIDs        []string               `protobuf:"bytes,3,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushMsgReq) Reset() {
	*x = PushMsgReq{}
	mi := &file_push_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReq) ProtoMessage() {}

func (x *PushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReq.ProtoReflect.Descriptor instead.
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *PushMsgReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *PushMsgReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type PushMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgResp) Reset() {
	*x = PushMsgResp{}
	mi := &file_push_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgResp) ProtoMessage() {}

func (x *PushMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgResp.ProtoReflect.Descriptor instead.
func (*PushMsgResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

// DelUserPushTokenReq forgets a device's push channels. An empty vendor
// forgets every channel the device registered (sign-out); a named one
// forgets only that one.
type DelUserPushTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	PlatformID    int32                  `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushTokenReq) Reset() {
	*x = DelUserPushTokenReq{}
	mi := &file_push_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushTokenReq) ProtoMessage() {}

func (x *DelUserPushTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushTokenReq.ProtoReflect.Descriptor instead.
func (*DelUserPushTokenReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{2}
}

func (x *DelUserPushTokenReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelUserPushTokenReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *DelUserPushTokenReq) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

type DelUserPushTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushTokenResp) Reset() {
	*x = DelUserPushTokenResp{}
	mi := &file_push_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushTokenResp) ProtoMessage() {}

func (x *DelUserPushTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushTokenResp.ProtoReflect.Descriptor instead.
func (*DelUserPushTokenResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{3}
}

type GetPushSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushSettingsReq) Reset() {
	*x = GetPushSettingsReq{}
	mi := &file_push_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushSettingsReq) ProtoMessage() {}

func (x *GetPushSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushSettingsReq.ProtoReflect.Descriptor instead.
func (*GetPushSettingsReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{4}
}

type GetPushSettingsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stored settings, secrets masked.
	Settings string `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings"`
	// Every field the console may show: path, type, label, options.
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema"`
	// The effective values after defaults, secrets masked.
	Effective  string `protobuf:"bytes,3,opt,name=effective,proto3" json:"effective"`
	Version    int64  `protobuf:"varint,4,opt,name=version,proto3" json:"version"`
	SeededFrom string `protobuf:"bytes,5,opt,name=seededFrom,proto3" json:"seededFrom"`
	SeededAt   int64  `protobuf:"varint,6,opt,name=seededAt,proto3" json:"seededAt"`
	UpdatedAt  int64  `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt"`
	UpdatedBy  string `protobuf:"bytes,8,opt,name=updatedBy,proto3" json:"updatedBy"`
	// Why the last reload of this instance failed, if it did.
	LastReloadError string `protobuf:"bytes,9,opt,name=lastReloadError,proto3" json:"lastReloadError"`
	// Whether this instance can store a new secret (settingsStore.secretKey set).
	CanStoreSecrets bool `protobuf:"varint,10,opt,name=canStoreSecrets,proto3" json:"canStoreSecrets"`
	// The offline push mode this service runs (openim-push.yml enable:).
	Mode          string `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushSettingsResp) Reset() {
	*x = GetPushSettingsResp{}
	mi := &file_push_push_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushSettingsResp) ProtoMessage() {}

func (x *GetPushSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushSettingsResp.ProtoReflect.Descriptor instead.
func (*GetPushSettingsResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{5}
}

func (x *GetPushSettingsResp) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *GetPushSettingsResp) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *GetPushSettingsResp) GetEffective() string {
	if x != nil {
		return x.Effective
	}
	return ""
}

func (x *GetPushSettingsResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetPushSettingsResp) GetSeededFrom() string {
	if x != nil {
		return x.SeededFrom
	}
	return ""
}

func (x *GetPushSettingsResp) GetSeededAt() int64 {
	if x != nil {
		return x.SeededAt
	}
	return 0
}

func (x *GetPushSettingsResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetPushSettingsResp) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *GetPushSettingsResp) GetLastReloadError() string {
	if x != nil {
		return x.LastReloadError
	}
	return ""
}

func (x *GetPushSettingsResp) GetCanStoreSecrets() bool {
	if x != nil {
		return x.CanStoreSecrets
	}
	return false
}

func (x *GetPushSettingsResp) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SetPushSettingsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A JSON object with only the fields to change. A secret is a string
	// to replace it, {"clear":true} to remove it; leaving it out (or "")
	// keeps it.
	Patch string `protobuf:"bytes,1,opt,name=patch,proto3" json:"patch"`
	// Who asked, for the audit trail: the console's own admin account.
	Operator      string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushSettingsReq) Reset() {
	*x = SetPushSettingsReq{}
	mi := &file_push_push_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushSettingsReq) ProtoMessage() {}

func (x *SetPushSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushSettingsReq.ProtoReflect.Descriptor instead.
func (*SetPushSettingsReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{6}
}

func (x *SetPushSettingsReq) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

func (x *SetPushSettingsReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type SetPushSettingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *GetPushSettingsResp   `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushSettingsResp) Reset() {
	*x = SetPushSettingsResp{}
	mi := &file_push_push_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushSettingsResp) ProtoMessage() {}

func (x *SetPushSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushSettingsResp.ProtoReflect.Descriptor instead.
func (*SetPushSettingsResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{7}
}

func (x *SetPushSettingsResp) GetSettings() *GetPushSettingsResp {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ImportPushSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportPushSettingsReq) Reset() {
	*x = ImportPushSettingsReq{}
	mi := &file_push_push_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportPushSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPushSettingsReq) ProtoMessage() {}

func (x *ImportPushSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPushSettingsReq.ProtoReflect.Descriptor instead.
func (*ImportPushSettingsReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{8}
}

func (x *ImportPushSettingsReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type ImportPushSettingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *GetPushSettingsResp   `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportPushSettingsResp) Reset() {
	*x = ImportPushSettingsResp{}
	mi := &file_push_push_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportPushSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPushSettingsResp) ProtoMessage() {}

func (x *ImportPushSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPushSettingsResp.ProtoReflect.Descriptor instead.
func (*ImportPushSettingsResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{9}
}

func (x *ImportPushSettingsResp) GetSettings() *GetPushSettingsResp {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ExportPushSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPushSettingsReq) Reset() {
	*x = ExportPushSettingsReq{}
	mi := &file_push_push_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPushSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPushSettingsReq) ProtoMessage() {}

func (x *ExportPushSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPushSettingsReq.ProtoReflect.Descriptor instead.
func (*ExportPushSettingsReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{10}
}

type ExportPushSettingsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YAML for openim-push.yml's settings: section, secrets as "<set>".
	Yaml          string `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPushSettingsResp) Reset() {
	*x = ExportPushSettingsResp{}
	mi := &file_push_push_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPushSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPushSettingsResp) ProtoMessage() {}

func (x *ExportPushSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPushSettingsResp.ProtoReflect.Descriptor instead.
func (*ExportPushSettingsResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{11}
}

func (x *ExportPushSettingsResp) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type VerifyPushProviderReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fcm, hms, honor, xiaomi, oppo, vivo.
	Provider      string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider"`
	Operator      string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPushProviderReq) Reset() {
	*x = VerifyPushProviderReq{}
	mi := &file_push_push_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPushProviderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPushProviderReq) ProtoMessage() {}

func (x *VerifyPushProviderReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPushProviderReq.ProtoReflect.Descriptor instead.
func (*VerifyPushProviderReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyPushProviderReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *VerifyPushProviderReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type VerifyPushProviderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latencyMs,proto3" json:"latencyMs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPushProviderResp) Reset() {
	*x = VerifyPushProviderResp{}
	mi := &file_push_push_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPushProviderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPushProviderResp) ProtoMessage() {}

func (x *VerifyPushProviderResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPushProviderResp.ProtoReflect.Descriptor instead.
func (*VerifyPushProviderResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyPushProviderResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyPushProviderResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VerifyPushProviderResp) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type TestPushReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserID string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	// "auto" routes as a real push would; a provider name forces that one.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider"`
	// message or callRing.
	Kind          string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind"`
	Operator      string `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPushReq) Reset() {
	*x = TestPushReq{}
	mi := &file_push_push_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPushReq) ProtoMessage() {}

func (x *TestPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPushReq.ProtoReflect.Descriptor instead.
func (*TestPushReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{14}
}

func (x *TestPushReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *TestPushReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TestPushReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TestPushReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type TestPushResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PlatformID int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID"`
	Provider   string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider"`
	TokenHint  string                 `protobuf:"bytes,3,opt,name=tokenHint,proto3" json:"tokenHint"`
	Ok         bool                   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok"`
	Error      string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error"`
	// A fallback to FCM after the vendor refused.
	Fallback      bool `protobuf:"varint,6,opt,name=fallback,proto3" json:"fallback"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPushResult) Reset() {
	*x = TestPushResult{}
	mi := &file_push_push_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPushResult) ProtoMessage() {}

func (x *TestPushResult) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPushResult.ProtoReflect.Descriptor instead.
func (*TestPushResult) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{15}
}

func (x *TestPushResult) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *TestPushResult) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TestPushResult) GetTokenHint() string {
	if x != nil {
		return x.TokenHint
	}
	return ""
}

func (x *TestPushResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestPushResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TestPushResult) GetFallback() bool {
	if x != nil {
		return x.Fallback
	}
	return false
}

type TestPushResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TestPushResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPushResp) Reset() {
	*x = TestPushResp{}
	mi := &file_push_push_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPushResp) ProtoMessage() {}

func (x *TestPushResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPushResp.ProtoReflect.Descriptor instead.
func (*TestPushResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{16}
}

func (x *TestPushResp) GetResults() []*TestPushResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PushDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor"`
	TokenHint     string                 `protobuf:"bytes,3,opt,name=tokenHint,proto3" json:"tokenHint"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region"`
	Locale        string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt"`
	LastResult    string                 `protobuf:"bytes,7,opt,name=lastResult,proto3" json:"lastResult"`
	LastError     string                 `protobuf:"bytes,8,opt,name=lastError,proto3" json:"lastError"`
	LastSentAt    int64                  `protobuf:"varint,9,opt,name=lastSentAt,proto3" json:"lastSentAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDevice) Reset() {
	*x = PushDevice{}
	mi := &file_push_push_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDevice) ProtoMessage() {}

func (x *PushDevice) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDevice.ProtoReflect.Descriptor instead.
func (*PushDevice) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{17}
}

func (x *PushDevice) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *PushDevice) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PushDevice) GetTokenHint() string {
	if x != nil {
		return x.TokenHint
	}
	return ""
}

func (x *PushDevice) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PushDevice) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *PushDevice) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PushDevice) GetLastResult() string {
	if x != nil {
		return x.LastResult
	}
	return ""
}

func (x *PushDevice) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *PushDevice) GetLastSentAt() int64 {
	if x != nil {
		return x.LastSentAt
	}
	return 0
}

type GetUserPushDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPushDevicesReq) Reset() {
	*x = GetUserPushDevicesReq{}
	mi := &file_push_push_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPushDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPushDevicesReq) ProtoMessage() {}

func (x *GetUserPushDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPushDevicesReq.ProtoReflect.Descriptor instead.
func (*GetUserPushDevicesReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserPushDevicesReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetUserPushDevicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*PushDevice          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPushDevicesResp) Reset() {
	*x = GetUserPushDevicesResp{}
	mi := &file_push_push_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPushDevicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPushDevicesResp) ProtoMessage() {}

func (x *GetUserPushDevicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPushDevicesResp.ProtoReflect.Descriptor instead.
func (*GetUserPushDevicesResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserPushDevicesResp) GetDevices() []*PushDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DelUserPushDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	PlatformID    int32                  `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushDeviceReq) Reset() {
	*x = DelUserPushDeviceReq{}
	mi := &file_push_push_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushDeviceReq) ProtoMessage() {}

func (x *DelUserPushDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushDeviceReq.ProtoReflect.Descriptor instead.
func (*DelUserPushDeviceReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{20}
}

func (x *DelUserPushDeviceReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelUserPushDeviceReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *DelUserPushDeviceReq) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *DelUserPushDeviceReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type DelUserPushDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushDeviceResp) Reset() {
	*x = DelUserPushDeviceResp{}
	mi := &file_push_push_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushDeviceResp) ProtoMessage() {}

func (x *DelUserPushDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushDeviceResp.ProtoReflect.Descriptor instead.
func (*DelUserPushDeviceResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{21}
}

type PushStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// yyyymmdd, UTC.
	Date     string `protobuf:"bytes,1,opt,name=date,proto3" json:"date"`
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider"`
	// sent, failed, dead, fallback, quota.
	Outcome       string `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome"`
	Count         int64  `protobuf:"varint,4,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStat) Reset() {
	*x = PushStat{}
	mi := &file_push_push_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStat) ProtoMessage() {}

func (x *PushStat) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStat.ProtoReflect.Descriptor instead.
func (*PushStat) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{22}
}

func (x *PushStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PushStat) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PushStat) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *PushStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetPushStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushStatsReq) Reset() {
	*x = GetPushStatsReq{}
	mi := &file_push_push_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushStatsReq) ProtoMessage() {}

func (x *GetPushStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushStatsReq.ProtoReflect.Descriptor instead.
func (*GetPushStatsReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{23}
}

func (x *GetPushStatsReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetPushStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*PushStat            `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushStatsResp) Reset() {
	*x = GetPushStatsResp{}
	mi := &file_push_push_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushStatsResp) ProtoMessage() {}

func (x *GetPushStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushStatsResp.ProtoReflect.Descriptor instead.
func (*GetPushStatsResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{24}
}

func (x *GetPushStatsResp) GetStats() []*PushStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type PushSettingsAudit struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	At       int64                  `protobuf:"varint,1,opt,name=at,proto3" json:"at"`
	Operator string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator"`
	// seed, fill, set, import, verify, test, delDevice.
	Action        string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action"`
	Fields        []string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields"`
	Detail        string   `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSettingsAudit) Reset() {
	*x = PushSettingsAudit{}
	mi := &file_push_push_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSettingsAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSettingsAudit) ProtoMessage() {}

func (x *PushSettingsAudit) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSettingsAudit.ProtoReflect.Descriptor instead.
func (*PushSettingsAudit) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{25}
}

func (x *PushSettingsAudit) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *PushSettingsAudit) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *PushSettingsAudit) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PushSettingsAudit) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PushSettingsAudit) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type GetPushSettingsAuditReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushSettingsAuditReq) Reset() {
	*x = GetPushSettingsAuditReq{}
	mi := &file_push_push_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushSettingsAuditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushSettingsAuditReq) ProtoMessage() {}

func (x *GetPushSettingsAuditReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushSettingsAuditReq.ProtoReflect.Descriptor instead.
func (*GetPushSettingsAuditReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{26}
}

func (x *GetPushSettingsAuditReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPushSettingsAuditResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PushSettingsAudit   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushSettingsAuditResp) Reset() {
	*x = GetPushSettingsAuditResp{}
	mi := &file_push_push_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushSettingsAuditResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushSettingsAuditResp) ProtoMessage() {}

func (x *GetPushSettingsAuditResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushSettingsAuditResp.ProtoReflect.Descriptor instead.
func (*GetPushSettingsAuditResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{27}
}

func (x *GetPushSettingsAuditResp) GetEntries() []*PushSettingsAudit {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_push_push_proto protoreflect.FileDescriptor

const file_push_push_proto_rawDesc = "" +
	"\n" +
	"\x0fpush/push.proto\x12\vopenim.push\x1a\x11sdkws/sdkws.proto\"\x7f\n" +
	"\n" +
	"PushMsgReq\x12/\n" +
	"\amsgData\x18\x01 \x01(\v2\x15.openim.sdkws.MsgDataR\amsgData\x12&\n" +
	"\x0econversationID\x18\x02 \x01(\tR\x0econversationID\x12\x18\n" +
	"\auserIDs\x18\x03 \x03(\tR\auserIDs\"\r\n" +
	"\vPushMsgResp\"e\n" +
	"\x13DelUserPushTokenReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"platformID\x18\x02 \x01(\x05R\n" +
	"platformID\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\"\x16\n" +
	"\x14DelUserPushTokenResp\"\x14\n" +
	"\x12GetPushSettingsReq\"\xe1\x02\n" +
	"\x13GetPushSettingsResp\x12\x1a\n" +
	"\bsettings\x18\x01 \x01(\tR\bsettings\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x1c\n" +
	"\teffective\x18\x03 \x01(\tR\teffective\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1e\n" +
	"\n" +
	"seededFrom\x18\x05 \x01(\tR\n" +
	"seededFrom\x12\x1a\n" +
	"\bseededAt\x18\x06 \x01(\x03R\bseededAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tupdatedBy\x18\b \x01(\tR\tupdatedBy\x12(\n" +
	"\x0flastReloadError\x18\t \x01(\tR\x0flastReloadError\x12(\n" +
	"\x0fcanStoreSecrets\x18\n" +
	" \x01(\bR\x0fcanStoreSecrets\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\"F\n" +
	"\x12SetPushSettingsReq\x12\x14\n" +
	"\x05patch\x18\x01 \x01(\tR\x05patch\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\"S\n" +
	"\x13SetPushSettingsResp\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .openim.push.GetPushSettingsRespR\bsettings\"3\n" +
	"\x15ImportPushSettingsReq\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\"V\n" +
	"\x16ImportPushSettingsResp\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .openim.push.GetPushSettingsRespR\bsettings\"\x17\n" +
	"\x15ExportPushSettingsReq\",\n" +
	"\x16ExportPushSettingsResp\x12\x12\n" +
	"\x04yaml\x18\x01 \x01(\tR\x04yaml\"O\n" +
	"\x15VerifyPushProviderReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\"\\\n" +
	"\x16VerifyPushProviderResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\tlatencyMs\x18\x03 \x01(\x03R\tlatencyMs\"q\n" +
	"\vTestPushReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\"\xac\x01\n" +
	"\x0eTestPushResult\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1c\n" +
	"\ttokenHint\x18\x03 \x01(\tR\ttokenHint\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\bfallback\x18\x06 \x01(\bR\bfallback\"E\n" +
	"\fTestPushResp\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.openim.push.TestPushResultR\aresults\"\x8e\x02\n" +
	"\n" +
	"PushDevice\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x1c\n" +
	"\ttokenHint\x18\x03 \x01(\tR\ttokenHint\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"lastResult\x18\a \x01(\tR\n" +
	"lastResult\x12\x1c\n" +
	"\tlastError\x18\b \x01(\tR\tlastError\x12\x1e\n" +
	"\n" +
	"lastSentAt\x18\t \x01(\x03R\n" +
	"lastSentAt\"/\n" +
	"\x15GetUserPushDevicesReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"K\n" +
	"\x16GetUserPushDevicesResp\x121\n" +
	"\adevices\x18\x01 \x03(\v2\x17.openim.push.PushDeviceR\adevices\"\x82\x01\n" +
	"\x14DelUserPushDeviceReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"platformID\x18\x02 \x01(\x05R\n" +
	"platformID\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\"\x17\n" +
	"\x15DelUserPushDeviceResp\"j\n" +
	"\bPushStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"%\n" +
	"\x0fGetPushStatsReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"?\n" +
	"\x10GetPushStatsResp\x12+\n" +
	"\x05stats\x18\x01 \x03(\v2\x15.openim.push.PushStatR\x05stats\"\x87\x01\n" +
	"\x11PushSettingsAudit\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\x03R\x02at\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06fields\x18\x04 \x03(\tR\x06fields\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"/\n" +
	"\x17GetPushSettingsAuditReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"T\n" +
	"\x18GetPushSettingsAuditResp\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.openim.push.PushSettingsAuditR\aentries2\x9e\b\n" +
	"\x0ePushMsgService\x12<\n" +
	"\aPushMsg\x12\x17.openim.push.PushMsgReq\x1a\x18.openim.push.PushMsgResp\x12W\n" +
	"\x10DelUserPushToken\x12 .openim.push.DelUserPushTokenReq\x1a!.openim.push.DelUserPushTokenResp\x12T\n" +
	"\x0fGetPushSettings\x12\x1f.openim.push.GetPushSettingsReq\x1a .openim.push.GetPushSettingsResp\x12T\n" +
	"\x0fSetPushSettings\x12\x1f.openim.push.SetPushSettingsReq\x1a .openim.push.SetPushSettingsResp\x12]\n" +
	"\x12ImportPushSettings\x12\".openim.push.ImportPushSettingsReq\x1a#.openim.push.ImportPushSettingsResp\x12]\n" +
	"\x12ExportPushSettings\x12\".openim.push.ExportPushSettingsReq\x1a#.openim.push.ExportPushSettingsResp\x12]\n" +
	"\x12VerifyPushProvider\x12\".openim.push.VerifyPushProviderReq\x1a#.openim.push.VerifyPushProviderResp\x12?\n" +
	"\bTestPush\x12\x18.openim.push.TestPushReq\x1a\x19.openim.push.TestPushResp\x12]\n" +
	"\x12GetUserPushDevices\x12\".openim.push.GetUserPushDevicesReq\x1a#.openim.push.GetUserPushDevicesResp\x12Z\n" +
	"\x11DelUserPushDevice\x12!.openim.push.DelUserPushDeviceReq\x1a\".openim.push.DelUserPushDeviceResp\x12K\n" +
	"\fGetPushStats\x12\x1c.openim.push.GetPushStatsReq\x1a\x1d.openim.push.GetPushStatsResp\x12c\n" +
	"\x14GetPushSettingsAudit\x12$.openim.push.GetPushSettingsAuditReq\x1a%.openim.push.GetPushSettingsAuditRespB$Z\"github.com/openimsdk/protocol/pushb\x06proto3"

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData []byte
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)))
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_push_push_proto_goTypes = []any{
	(*PushMsgReq)(nil),               // 0: openim.push.PushMsgReq
	(*PushMsgResp)(nil),              // 1: openim.push.PushMsgResp
	(*DelUserPushTokenReq)(nil),      // 2: openim.push.DelUserPushTokenReq
	(*DelUserPushTokenResp)(nil),     // 3: openim.push.DelUserPushTokenResp
	(*GetPushSettingsReq)(nil),       // 4: openim.push.GetPushSettingsReq
	(*GetPushSettingsResp)(nil),      // 5: openim.push.GetPushSettingsResp
	(*SetPushSettingsReq)(nil),       // 6: openim.push.SetPushSettingsReq
	(*SetPushSettingsResp)(nil),      // 7: openim.push.SetPushSettingsResp
	(*ImportPushSettingsReq)(nil),    // 8: openim.push.ImportPushSettingsReq
	(*ImportPushSettingsResp)(nil),   // 9: openim.push.ImportPushSettingsResp
	(*ExportPushSettingsReq)(nil),    // 10: openim.push.ExportPushSettingsReq
	(*ExportPushSettingsResp)(nil),   // 11: openim.push.ExportPushSettingsResp
	(*VerifyPushProviderReq)(nil),    // 12: openim.push.VerifyPushProviderReq
	(*VerifyPushProviderResp)(nil),   // 13: openim.push.VerifyPushProviderResp
	(*TestPushReq)(nil),              // 14: openim.push.TestPushReq
	(*TestPushResult)(nil),           // 15: openim.push.TestPushResult
	(*TestPushResp)(nil),             // 16: openim.push.TestPushResp
	(*PushDevice)(nil),               // 17: openim.push.PushDevice
	(*GetUserPushDevicesReq)(nil),    // 18: openim.push.GetUserPushDevicesReq
	(*GetUserPushDevicesResp)(nil),   // 19: openim.push.GetUserPushDevicesResp
	(*DelUserPushDeviceReq)(nil),     // 20: openim.push.DelUserPushDeviceReq
	(*DelUserPushDeviceResp)(nil),    // 21: openim.push.DelUserPushDeviceResp
	(*PushStat)(nil),                 // 22: openim.push.PushStat
	(*GetPushStatsReq)(nil),          // 23: openim.push.GetPushStatsReq
	(*GetPushStatsResp)(nil),         // 24: openim.push.GetPushStatsResp
	(*PushSettingsAudit)(nil),        // 25: openim.push.PushSettingsAudit
	(*GetPushSettingsAuditReq)(nil),  // 26: openim.push.GetPushSettingsAuditReq
	(*GetPushSettingsAuditResp)(nil), // 27: openim.push.GetPushSettingsAuditResp
	(*sdkws.MsgData)(nil),            // 28: openim.sdkws.MsgData
}
var file_push_push_proto_depIdxs = []int32{
	28, // 0: openim.push.PushMsgReq.msgData:type_name -> openim.sdkws.MsgData
	5,  // 1: openim.push.SetPushSettingsResp.settings:type_name -> openim.push.GetPushSettingsResp
	5,  // 2: openim.push.ImportPushSettingsResp.settings:type_name -> openim.push.GetPushSettingsResp
	15, // 3: openim.push.TestPushResp.results:type_name -> openim.push.TestPushResult
	17, // 4: openim.push.GetUserPushDevicesResp.devices:type_name -> openim.push.PushDevice
	22, // 5: openim.push.GetPushStatsResp.stats:type_name -> openim.push.PushStat
	25, // 6: openim.push.GetPushSettingsAuditResp.entries:type_name -> openim.push.PushSettingsAudit
	0,  // 7: openim.push.PushMsgService.PushMsg:input_type -> openim.push.PushMsgReq
	2,  // 8: openim.push.PushMsgService.DelUserPushToken:input_type -> openim.push.DelUserPushTokenReq
	4,  // 9: openim.push.PushMsgService.GetPushSettings:input_type -> openim.push.GetPushSettingsReq
	6,  // 10: openim.push.PushMsgService.SetPushSettings:input_type -> openim.push.SetPushSettingsReq
	8,  // 11: openim.push.PushMsgService.ImportPushSettings:input_type -> openim.push.ImportPushSettingsReq
	10, // 12: openim.push.PushMsgService.ExportPushSettings:input_type -> openim.push.ExportPushSettingsReq
	12, // 13: openim.push.PushMsgService.VerifyPushProvider:input_type -> openim.push.VerifyPushProviderReq
	14, // 14: openim.push.PushMsgService.TestPush:input_type -> openim.push.TestPushReq
	18, // 15: openim.push.PushMsgService.GetUserPushDevices:input_type -> openim.push.GetUserPushDevicesReq
	20, // 16: openim.push.PushMsgService.DelUserPushDevice:input_type -> openim.push.DelUserPushDeviceReq
	23, // 17: openim.push.PushMsgService.GetPushStats:input_type -> openim.push.GetPushStatsReq
	26, // 18: openim.push.PushMsgService.GetPushSettingsAudit:input_type -> openim.push.GetPushSettingsAuditReq
	1,  // 19: openim.push.PushMsgService.PushMsg:output_type -> openim.push.PushMsgResp
	3,  // 20: openim.push.PushMsgService.DelUserPushToken:output_type -> openim.push.DelUserPushTokenResp
	5,  // 21: openim.push.PushMsgService.GetPushSettings:output_type -> openim.push.GetPushSettingsResp
	7,  // 22: openim.push.PushMsgService.SetPushSettings:output_type -> openim.push.SetPushSettingsResp
	9,  // 23: openim.push.PushMsgService.ImportPushSettings:output_type -> openim.push.ImportPushSettingsResp
	11, // 24: openim.push.PushMsgService.ExportPushSettings:output_type -> openim.push.ExportPushSettingsResp
	13, // 25: openim.push.PushMsgService.VerifyPushProvider:output_type -> openim.push.VerifyPushProviderResp
	16, // 26: openim.push.PushMsgService.TestPush:output_type -> openim.push.TestPushResp
	19, // 27: openim.push.PushMsgService.GetUserPushDevices:output_type -> openim.push.GetUserPushDevicesResp
	21, // 28: openim.push.PushMsgService.DelUserPushDevice:output_type -> openim.push.DelUserPushDeviceResp
	24, // 29: openim.push.PushMsgService.GetPushStats:output_type -> openim.push.GetPushStatsResp
	27, // 30: openim.push.PushMsgService.GetPushSettingsAudit:output_type -> openim.push.GetPushSettingsAuditResp
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
